language: ruby
script: 'bundle exec rake spec'
rvm:
  - 1.9.3
  - 2.0.0
  - ruby
  - jruby
  - rbx-head
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
